apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment 
  namespace: my-app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: daria1kulsitova/backend
        ports:
          - containerPort: 8000
        env:
        - name: DB_HOST
          value: "postgresql-service"
        - name: DB_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-db
        volumeMounts:
        - name: static-files
          mountPath: /staticfiles
        command: ["/bin/sh", "-c"]
        args:
          - |
            python manage.py collectstatic --noinput &&
            gunicorn --bind 0.0.0.0:8000 backend.wsgi
      volumes:
      - name: static-files
        persistentVolumeClaim:
          claimName: static-files-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1