apiVersion: v1
kind: PersistentVolume
{{- with .Values.staticFilesVolume }}
metadata:
  name: {{ .name }}-pv
  namespace: {{ $.Release.Namespace }}
spec:
  capacity:
    storage: {{ .storage }}
  accessModes:
{{- toYaml .accessModes | nindent 4}}
  hostPath:
    path: {{ .pv.hostPath.path }}
    type: {{ .pv.hostPath.type }}
{{- end }}