apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.staticFilesVolume.name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
{{- toYaml .Values.staticFilesVolume.accessModes | nindent 4}}
  resources:
    requests:
      storage: {{ .Values.staticFilesVolume.storage }}