apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: my-app
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: daria1kulsitova/backend
        command: ["python", "manage.py", "migrate"]
        env:
        - name: DB_HOST
          value: "postgresql-service"
        - name: DB_PORT  
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-db
      restartPolicy: Never
  backoffLimit: 2