apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-files-pv
  namespace: my-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/static-files
    type: DirectoryOrCreate