apiVersion: apps/v2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment 
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "backend.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
{{ include "backend.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "backend.labels" . | indent 8 }}
    spec:
    {{- with .Values.deployment.spec.template.spec.containers }}
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        ports:
          - containerPort: {{ $.Values.service.ports.targetPort }}
        env:
        {{- range $key, $val := $.Values.env.values}}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        {{- range $key, $val := $.Values.env.secret}}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.global.secret.name }}
              key: {{ $val }}
        {{- end }}
        volumeMounts:
        - name: {{ .volumeMounts.name }}
          mountPath: {{ .volumeMounts.mountPath }}
        command:{{- toYaml .command | nindent 10 }}
        args:
          {{- toYaml .args | nindent 10 }}
    {{- end }}
      volumes:
      - name: {{ .Values.deployment.spec.template.spec.volumes.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.deployment.spec.template.spec.volumes.persistentVolumeClaim.claimName }}
  strategy:
{{- toYaml .Values.deployment.spec.strategy | nindent 4}}