apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "backend.labels" . | indent 4 }}
type: {{ .Values.secret.type }}
data:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}