apiVersion: {{ .Chart.apiVersion }}
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "postgres.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  selector:
{{ include "postgres.selectorLabels" . | indent 4 }}
  {{- with .Values.service.ports }}
  ports:
    - protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}