global:
  secret:
    name: db-secret
  service:
    backend: backend-service
    frontend: frontend-service

ingress:
  spec:
    rules:
      - host: taski-app.localhost.ru
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80

static-files-volume:
  name: static-files
  storage: 1Gi
  accessModes:
    - ReadWriteOnce
  pv:
    hostPath:
      path: /data/static-files
      type: DirectoryOrCreate

