env:
  values:
    DB_HOST: postgres-service
    DB_PORT: 5432
    REDIS_HOST: redis-master.redis.svc.cluster.local
    REDIS_PORT: 6379
    DEFAULT_CACHE_TTL: 86400
  secret:
    db:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: postgres-db
    redis:
      REDIS_DB: db
      REDIS_PASSWORD: password
      REDIS_USERNAME: username

service:
  spec:
    type: NodePort
  ports:
    protocol: TCP
    port: 3030
    targetPort: 8000

job:
  metadata:
    name: django-migrate
  spec:
    template:
      spec:
        containers:
          name: migrate
          image: daria1kulsitova/backend
          command: ["python", "manage.py", "migrate"]
          restartPolicy: Never
    backoffLimit: 2

deployment:
  replicas: 1
  spec:
    template:
      spec:
        containers:
          name: backend
          image: daria1kulsitova/backend:1.1.0
          volumeMounts:
            name: static-files
            mountPath: /staticfiles
          command: ["/bin/sh", "-c"]
          args:
            - "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 backend.wsgi"
        volumes:
          name: static-files
          persistentVolumeClaim:
            claimName: static-files-pvc
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1

secret:
  type: Opaque