apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment 
  namespace: {{ .Release.Namespace}}
  labels:
{{ include "nginx.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
{{ include "nginx.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "nginx.labels" . | indent 8 }}
    spec:
    {{- with .Values.deployment.spec.template.spec.containers }}
      containers:
      - name: {{ .name }}
        image: {{ printf "%s:%s" .image.name .image.tag}}
        ports:
          - containerPort: {{ $.Values.service.ports.targetPort }}
        volumeMounts:
{{- toYaml .volumeMounts | nindent 10 }}
    {{- end}}
      volumes:
{{- toYaml .Values.deployment.spec.template.spec.volumes | nindent 8 }}
  strategy:
{{- toYaml .Values.deployment.spec.strategy | nindent 4}}